FROM python:3.8-slim
ENV PORT=8080

RUN mkdir /app
WORKDIR /app

COPY . /app
RUN pip3 install -r requirements.txt

EXPOSE ${PORT}
CMD exec gunicorn --bind :${PORT} --workers 1 --worker-class uvicorn.workers.UvicornWorker  --threads 8 main:app
